projects:
  loco:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: pcxj3iu3wzb35lgm25xi5nfunu
      endpoints:
        prod: >-
          https://bsruzfsz7vcffedtcfnau2tdyu.appsync-api.us-east-1.amazonaws.com/graphql
