// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f9708330-4025-40e2-8c80-f1f24eed514c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9fvmexsr6",
    "aws_user_pools_web_client_id": "5h3kokhpnc8gn4ss7ib7d14g79",
    "aws_appsync_graphqlEndpoint": "https://bsruzfsz7vcffedtcfnau2tdyu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
