// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d5d867b2-1ebe-45b3-ac31-ec1d3152cc7a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YzkckPdDZ",
    "aws_user_pools_web_client_id": "7c8crtheemq4qa3jr3em37ovrt",
    "aws_appsync_graphqlEndpoint": "https://cuql6pzns5fbtnhcrouhbnr754.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
